import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
/*const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   
}; */

/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */

// Sidebar configuration
module.exports = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'The Autobot Candidate',
      items: [
        'autobot-candidate/overview',
        'autobot-candidate/system-requirements',
        'autobot-candidate/setting-up-development-environment',
        'autobot-candidate/cloning-repos',
        'autobot-candidate/installing-dependencies',
        'autobot-candidate/running-app',
        //'autobot-candidate/connecting-to-admin',
        //'autobot-candidate/verifying-connection',
        'autobot-candidate/app-components',
        'autobot-candidate/building-for-distribution',
      ],
    },
    {
      type: 'category',
      label: 'The Autobot Admin',
      items: [
        'autobot-admin/overview',
        //'autobot-admin/overview',
        'autobot-admin/setting-up-development-environment',
        'autobot-admin/app-components',
        'autobot-admin/default-controller',
        'autobot-admin/center-package/center-controller',
        'autobot-admin/center-package/center-dtos',
        'autobot-admin/center-package/center-entity',
        'autobot-admin/center-package/center-repository',
        'autobot-admin/center-package/center-service',
        'autobot-admin/center-package/overview',
        'autobot-admin/center-package/utilities',
        {
          type: 'category',
          label: 'Client Node Package',
          items: [
            'autobot-admin/client-node-package/overview',
            'autobot-admin/client-node-package/entity',
            'autobot-admin/client-node-package/client-node-controller',
            'autobot-admin/client-node-package/dtos',
            'autobot-admin/client-node-package/repository',
            'autobot-admin/client-node-package/services',
            'autobot-admin/client-node-package/utilities',
          ],
        },
        {
          type: 'category',
          label: 'Exam Package',
          items: [
            'autobot-admin/exam-package/overview',
            'autobot-admin/exam-package/dtos',
            'autobot-admin/exam-package/exam-controller',
            'autobot-admin/exam-package/exam-memory-impl',
            'autobot-admin/exam-package/exam-service',
            'autobot-admin/exam-package/other-controllers',
            'autobot-admin/exam-package/repositories',
            'autobot-admin/exam-package/utilities',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'The Autobot Server',
      items: [
        'autobot-server/overview',
        'autobot-server/system-requirements',
        'autobot-server/setting-up-development-environment',
        'autobot-server/cloning-repos',
        'autobot-server/installing-dependencies',
        'autobot-server/environmental-variables',
        'autobot-server/running-app',
        'autobot-server/deploying-to-lambda',
        'autobot-server/app-components',
      ],
    },
  ],
};
